language:
  language-name: Java 17.0.0 - Modified by Daniel
server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
 
